INFO 2025-04-30 22:35:47,066 autoreload 13108 16276 Watching for file changes with StatReloader
INFO 2025-04-30 23:03:10,394 autoreload 9724 1900 Watching for file changes with StatReloader
INFO 2025-04-30 23:03:53,941 autoreload 9724 1900 G:\我的文档\文档\GitHub\sdsyxyq\users\models.py changed, reloading.
INFO 2025-04-30 23:03:54,650 autoreload 16320 13380 Watching for file changes with StatReloader
INFO 2025-04-30 23:04:57,344 autoreload 3792 4596 Watching for file changes with StatReloader
INFO 2025-04-30 23:06:26,005 autoreload 3792 4596 G:\我的文档\文档\GitHub\sdsyxyq\users\views.py changed, reloading.
INFO 2025-04-30 23:06:26,695 autoreload 4448 7308 Watching for file changes with StatReloader
ERROR 2025-04-30 23:06:34,194 log 4448 10476 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "G:\我的文档\文档\GitHub\sdsyxyq\users\middleware.py", line 11, in __call__
    if request.user.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'user'
ERROR 2025-04-30 23:06:34,196 basehttp 4448 10476 "GET / HTTP/1.1" 500 66125
ERROR 2025-04-30 23:10:39,477 log 4448 14020 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "G:\我的文档\文档\GitHub\sdsyxyq\users\middleware.py", line 11, in __call__
    if request.user.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'user'
ERROR 2025-04-30 23:10:39,478 basehttp 4448 14020 "GET /admin/ HTTP/1.1" 500 65893
INFO 2025-04-30 23:38:00,152 autoreload 4448 7308 G:\我的文档\文档\GitHub\sdsyxyq\xyq\settings.py changed, reloading.
INFO 2025-04-30 23:38:00,882 autoreload 14920 15136 Watching for file changes with StatReloader
INFO 2025-04-30 23:38:04,837 autoreload 14920 15136 G:\我的文档\文档\GitHub\sdsyxyq\xyq\settings.py changed, reloading.
INFO 2025-04-30 23:38:05,582 autoreload 17240 16876 Watching for file changes with StatReloader
INFO 2025-04-30 23:39:38,742 autoreload 17240 16876 G:\我的文档\文档\GitHub\sdsyxyq\users\models.py changed, reloading.
INFO 2025-04-30 23:39:39,517 autoreload 10756 12416 Watching for file changes with StatReloader
INFO 2025-04-30 23:39:59,547 autoreload 10756 12416 G:\我的文档\文档\GitHub\sdsyxyq\users\middleware.py changed, reloading.
INFO 2025-04-30 23:40:00,227 autoreload 13668 4064 Watching for file changes with StatReloader
INFO 2025-04-30 23:40:34,238 autoreload 13668 4064 G:\我的文档\文档\GitHub\sdsyxyq\users\views.py changed, reloading.
INFO 2025-04-30 23:40:34,974 autoreload 15932 16196 Watching for file changes with StatReloader
ERROR 2025-04-30 23:40:42,387 log 15932 14368 Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: users_banneduser

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "G:\我的文档\文档\GitHub\sdsyxyq\users\middleware.py", line 14, in __call__
    banned_user = BannedUser.objects.get(user=request.user)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\WY\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: users_banneduser
ERROR 2025-04-30 23:40:42,391 basehttp 15932 14368 "GET /admin/ HTTP/1.1" 500 136896
INFO 2025-04-30 23:41:18,306 basehttp 15932 14368 "GET /admin/ HTTP/1.1" 302 0
INFO 2025-04-30 23:41:18,454 basehttp 15932 14368 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 3686
INFO 2025-04-30 23:41:18,635 basehttp 15932 14368 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2025-04-30 23:41:22,425 basehttp 15932 14368 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2025-04-30 23:41:22,562 basehttp 15932 14368 "GET /admin/ HTTP/1.1" 200 11612
INFO 2025-04-30 23:41:25,318 basehttp 15932 14368 "GET /admin/users/customuser/ HTTP/1.1" 200 52063
INFO 2025-04-30 23:41:25,463 basehttp 15932 14368 "GET /admin/jsi18n/ HTTP/1.1" 200 8560
INFO 2025-04-30 23:41:28,961 basehttp 15932 14368 "GET /admin/users/customuser/125/change/ HTTP/1.1" 200 24414
INFO 2025-04-30 23:41:28,977 basehttp 15932 14496 "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
INFO 2025-04-30 23:41:28,999 basehttp 15932 14852 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-04-30 23:41:29,001 basehttp 15932 14368 "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
INFO 2025-04-30 23:41:29,001 basehttp 15932 16492 "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15292
INFO 2025-04-30 23:41:29,100 basehttp 15932 16476 "GET /admin/jsi18n/ HTTP/1.1" 200 8560
INFO 2025-04-30 23:41:29,154 basehttp 15932 16476 "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
INFO 2025-04-30 23:41:29,155 basehttp 15932 14496 "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-04-30 23:41:29,155 basehttp 15932 14852 "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-04-30 23:41:29,156 basehttp 15932 14368 "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
INFO 2025-04-30 23:41:29,163 basehttp 15932 16492 "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
INFO 2025-04-30 23:48:29,068 autoreload 15932 16196 G:\我的文档\文档\GitHub\sdsyxyq\users\models.py changed, reloading.
INFO 2025-04-30 23:48:29,844 autoreload 16296 10216 Watching for file changes with StatReloader
INFO 2025-04-30 23:49:01,653 autoreload 16296 10216 G:\我的文档\文档\GitHub\sdsyxyq\users\middleware.py changed, reloading.
INFO 2025-04-30 23:49:02,343 autoreload 16380 14636 Watching for file changes with StatReloader
INFO 2025-04-30 23:49:30,056 autoreload 16380 14636 G:\我的文档\文档\GitHub\sdsyxyq\users\views.py changed, reloading.
INFO 2025-04-30 23:49:30,858 autoreload 9308 9572 Watching for file changes with StatReloader
INFO 2025-04-30 23:49:44,380 autoreload 9308 9572 G:\我的文档\文档\GitHub\sdsyxyq\users\models.py changed, reloading.
INFO 2025-04-30 23:49:45,065 autoreload 6732 16332 Watching for file changes with StatReloader
INFO 2025-04-30 23:59:55,751 autoreload 16468 4316 Watching for file changes with StatReloader
INFO 2025-04-30 23:59:59,421 basehttp 16468 13448 "GET /admin/users/customuser/125/change/ HTTP/1.1" 200 24697
INFO 2025-04-30 23:59:59,541 basehttp 16468 13448 "GET /admin/jsi18n/ HTTP/1.1" 200 8560
INFO 2025-05-01 00:00:01,554 basehttp 16468 13448 "GET /admin/ HTTP/1.1" 200 11612
